// dataVehiclesElectricEU.js


const jsonChunk = `
[
 {
   "Brand": "Tesla ",
   "Model": "Model 3 Long Range Dual Motor",
   "AccelSec": 4.6,
   "TopSpeed_KmH": 233,
   "Range_Km": 450,
   "Efficiency_WhKm": 161,
   "FastCharge_KmH": "940",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 55480
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.3 Pure",
   "AccelSec": 10,
   "TopSpeed_KmH": 160,
   "Range_Km": 270,
   "Efficiency_WhKm": 167,
   "FastCharge_KmH": "250",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 30000
 },
 {
   "Brand": "Polestar ",
   "Model": "2",
   "AccelSec": 4.7,
   "TopSpeed_KmH": 210,
   "Range_Km": 400,
   "Efficiency_WhKm": 181,
   "FastCharge_KmH": "620",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Liftback",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 56440
 },
 {
   "Brand": "BMW ",
   "Model": "iX3 ",
   "AccelSec": 6.8,
   "TopSpeed_KmH": 180,
   "Range_Km": 360,
   "Efficiency_WhKm": 206,
   "FastCharge_KmH": "560",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 68040
 },
 {
   "Brand": "Honda ",
   "Model": "e ",
   "AccelSec": 9.5,
   "TopSpeed_KmH": 145,
   "Range_Km": 170,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "190",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 32997
 },
 {
   "Brand": "Lucid ",
   "Model": "Air ",
   "AccelSec": 2.8,
   "TopSpeed_KmH": 250,
   "Range_Km": 610,
   "Efficiency_WhKm": 180,
   "FastCharge_KmH": "620",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 5,
   "PriceEuro": 105000
 },
 {
   "Brand": "Volkswagen ",
   "Model": "e-Golf ",
   "AccelSec": 9.6,
   "TopSpeed_KmH": 150,
   "Range_Km": 190,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "220",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 31900
 },
 {
   "Brand": "Peugeot ",
   "Model": "e-208 ",
   "AccelSec": 8.1,
   "TopSpeed_KmH": 150,
   "Range_Km": 275,
   "Efficiency_WhKm": 164,
   "FastCharge_KmH": "420",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 29682
 },
 {
   "Brand": "Tesla ",
   "Model": "Model 3 Standard Range Plus",
   "AccelSec": 5.6,
   "TopSpeed_KmH": 225,
   "Range_Km": 310,
   "Efficiency_WhKm": 153,
   "FastCharge_KmH": "650",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 46380
 },
 {
   "Brand": "Audi ",
   "Model": "Q4 e-tron ",
   "AccelSec": 6.3,
   "TopSpeed_KmH": 180,
   "Range_Km": 400,
   "Efficiency_WhKm": 193,
   "FastCharge_KmH": "540",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 55000
 },
 {
   "Brand": "Mercedes ",
   "Model": "EQC 400 4MATIC",
   "AccelSec": 5.1,
   "TopSpeed_KmH": 180,
   "Range_Km": 370,
   "Efficiency_WhKm": 216,
   "FastCharge_KmH": "440",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 69484
 },
 {
   "Brand": "Nissan ",
   "Model": "Leaf ",
   "AccelSec": 7.9,
   "TopSpeed_KmH": 144,
   "Range_Km": 220,
   "Efficiency_WhKm": 164,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CHAdeMO",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 29234
 },
 {
   "Brand": "Hyundai ",
   "Model": "Kona Electric 64 kWh",
   "AccelSec": 7.9,
   "TopSpeed_KmH": 167,
   "Range_Km": 400,
   "Efficiency_WhKm": 160,
   "FastCharge_KmH": "380",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 40795
 },
 {
   "Brand": "BMW ",
   "Model": "i4 ",
   "AccelSec": 4,
   "TopSpeed_KmH": 200,
   "Range_Km": 450,
   "Efficiency_WhKm": 178,
   "FastCharge_KmH": "650",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 65000
 },
 {
   "Brand": "Hyundai ",
   "Model": "IONIQ Electric",
   "AccelSec": 9.7,
   "TopSpeed_KmH": 165,
   "Range_Km": 250,
   "Efficiency_WhKm": 153,
   "FastCharge_KmH": "210",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Liftback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 34459
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.3 Pro S",
   "AccelSec": 7.9,
   "TopSpeed_KmH": 160,
   "Range_Km": 440,
   "Efficiency_WhKm": 175,
   "FastCharge_KmH": "590",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 4,
   "PriceEuro": 40936
 },
 {
   "Brand": "Porsche ",
   "Model": "Taycan Turbo S",
   "AccelSec": 2.8,
   "TopSpeed_KmH": 260,
   "Range_Km": 375,
   "Efficiency_WhKm": 223,
   "FastCharge_KmH": "780",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 180781
 },
 {
   "Brand": "Volkswagen ",
   "Model": "e-Up! ",
   "AccelSec": 11.9,
   "TopSpeed_KmH": 130,
   "Range_Km": 195,
   "Efficiency_WhKm": 166,
   "FastCharge_KmH": "170",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 4,
   "PriceEuro": 21421
 },
 {
   "Brand": "MG ",
   "Model": "ZS EV",
   "AccelSec": 8.2,
   "TopSpeed_KmH": 140,
   "Range_Km": 220,
   "Efficiency_WhKm": 193,
   "FastCharge_KmH": "260",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 30000
 },
 {
   "Brand": "Mini ",
   "Model": "Cooper SE ",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 150,
   "Range_Km": 185,
   "Efficiency_WhKm": 156,
   "FastCharge_KmH": "260",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 31681
 },
 {
   "Brand": "Opel ",
   "Model": "Corsa-e ",
   "AccelSec": 8.1,
   "TopSpeed_KmH": 150,
   "Range_Km": 275,
   "Efficiency_WhKm": 164,
   "FastCharge_KmH": "420",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 29146
 },
 {
   "Brand": "Tesla ",
   "Model": "Model Y Long Range Dual Motor",
   "AccelSec": 5.1,
   "TopSpeed_KmH": 217,
   "Range_Km": 425,
   "Efficiency_WhKm": 171,
   "FastCharge_KmH": "930",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 7,
   "PriceEuro": 58620
 },
 {
   "Brand": "Skoda ",
   "Model": "Enyaq iV 50",
   "AccelSec": 10,
   "TopSpeed_KmH": 160,
   "Range_Km": 290,
   "Efficiency_WhKm": 179,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 35000
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron GT ",
   "AccelSec": 3.5,
   "TopSpeed_KmH": 240,
   "Range_Km": 425,
   "Efficiency_WhKm": 197,
   "FastCharge_KmH": "850",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 125000
 },
 {
   "Brand": "Tesla ",
   "Model": "Model 3 Long Range Performance",
   "AccelSec": 3.4,
   "TopSpeed_KmH": 261,
   "Range_Km": 435,
   "Efficiency_WhKm": 167,
   "FastCharge_KmH": "910",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 61480
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.4 ",
   "AccelSec": 7.5,
   "TopSpeed_KmH": 160,
   "Range_Km": 420,
   "Efficiency_WhKm": 183,
   "FastCharge_KmH": "560",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 45000
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.3 Pro",
   "AccelSec": 9,
   "TopSpeed_KmH": 160,
   "Range_Km": 350,
   "Efficiency_WhKm": 166,
   "FastCharge_KmH": "490",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 33000
 },
 {
   "Brand": "Volvo ",
   "Model": "XC40 P8 AWD Recharge",
   "AccelSec": 4.9,
   "TopSpeed_KmH": 180,
   "Range_Km": 375,
   "Efficiency_WhKm": 200,
   "FastCharge_KmH": "470",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 60437
 },
 {
   "Brand": "BMW ",
   "Model": "i3 120 Ah",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 150,
   "Range_Km": 235,
   "Efficiency_WhKm": 161,
   "FastCharge_KmH": "270",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 38017
 },
 {
   "Brand": "Peugeot ",
   "Model": "e-2008 SUV ",
   "AccelSec": 8.5,
   "TopSpeed_KmH": 150,
   "Range_Km": 250,
   "Efficiency_WhKm": 180,
   "FastCharge_KmH": "380",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 34361
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron 50 quattro",
   "AccelSec": 6.8,
   "TopSpeed_KmH": 190,
   "Range_Km": 280,
   "Efficiency_WhKm": 231,
   "FastCharge_KmH": "450",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 67358
 },
 {
   "Brand": "Kia ",
   "Model": "e-Niro 64 kWh",
   "AccelSec": 7.8,
   "TopSpeed_KmH": 167,
   "Range_Km": 370,
   "Efficiency_WhKm": 173,
   "FastCharge_KmH": "350",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 38105
 },
 {
   "Brand": "Renault ",
   "Model": "Zoe ZE50 R110",
   "AccelSec": 11.4,
   "TopSpeed_KmH": 135,
   "Range_Km": 315,
   "Efficiency_WhKm": 165,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 31184
 },
 {
   "Brand": "Tesla ",
   "Model": "Cybertruck Tri Motor",
   "AccelSec": 3,
   "TopSpeed_KmH": 210,
   "Range_Km": 750,
   "Efficiency_WhKm": 267,
   "FastCharge_KmH": "710",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Pickup",
   "Segment": "N",
   "Seats": 6,
   "PriceEuro": 75000
 },
 {
   "Brand": "Mazda ",
   "Model": "MX-30 ",
   "AccelSec": 9,
   "TopSpeed_KmH": 150,
   "Range_Km": 180,
   "Efficiency_WhKm": 178,
   "FastCharge_KmH": "240",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 32646
 },
 {
   "Brand": "Nissan ",
   "Model": "Leaf e+",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 157,
   "Range_Km": 325,
   "Efficiency_WhKm": 172,
   "FastCharge_KmH": "390",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CHAdeMO",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 37237
 },
 {
   "Brand": "Lexus ",
   "Model": "UX 300e",
   "AccelSec": 7.5,
   "TopSpeed_KmH": 160,
   "Range_Km": 270,
   "Efficiency_WhKm": 193,
   "FastCharge_KmH": "190",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CHAdeMO",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 50000
 },
 {
   "Brand": "CUPRA ",
   "Model": "el-Born ",
   "AccelSec": 6.5,
   "TopSpeed_KmH": 160,
   "Range_Km": 425,
   "Efficiency_WhKm": 181,
   "FastCharge_KmH": "570",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 4,
   "PriceEuro": 45000
 },
 {
   "Brand": "Renault ",
   "Model": "Zoe ZE50 R135",
   "AccelSec": 9.5,
   "TopSpeed_KmH": 140,
   "Range_Km": 310,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 33133
 },
 {
   "Brand": "Mercedes ",
   "Model": "EQA ",
   "AccelSec": 5,
   "TopSpeed_KmH": 200,
   "Range_Km": 350,
   "Efficiency_WhKm": 171,
   "FastCharge_KmH": "440",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 45000
 },
 {
   "Brand": "Tesla ",
   "Model": "Model S Long Range",
   "AccelSec": 3.8,
   "TopSpeed_KmH": 250,
   "Range_Km": 515,
   "Efficiency_WhKm": 184,
   "FastCharge_KmH": "560",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2",
   "BodyStyle": "Liftback",
   "Segment": "F",
   "Seats": 5,
   "PriceEuro": 79990
 },
 {
   "Brand": "Hyundai ",
   "Model": "Kona Electric 39 kWh",
   "AccelSec": 9.9,
   "TopSpeed_KmH": 155,
   "Range_Km": 255,
   "Efficiency_WhKm": 154,
   "FastCharge_KmH": "210",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 33971
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron Sportback 55 quattro",
   "AccelSec": 5.7,
   "TopSpeed_KmH": 200,
   "Range_Km": 380,
   "Efficiency_WhKm": 228,
   "FastCharge_KmH": "610",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 81639
 },
 {
   "Brand": "Skoda ",
   "Model": "CITIGOe iV ",
   "AccelSec": 12.3,
   "TopSpeed_KmH": 130,
   "Range_Km": 195,
   "Efficiency_WhKm": 166,
   "FastCharge_KmH": "170",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 4,
   "PriceEuro": 24534
 },
 {
   "Brand": "SEAT ",
   "Model": "Mii Electric ",
   "AccelSec": 12.3,
   "TopSpeed_KmH": 130,
   "Range_Km": 195,
   "Efficiency_WhKm": 166,
   "FastCharge_KmH": "170",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 4,
   "PriceEuro": 20129
 },
 {
   "Brand": "Kia ",
   "Model": "e-Soul 64 kWh",
   "AccelSec": 7.9,
   "TopSpeed_KmH": 167,
   "Range_Km": 365,
   "Efficiency_WhKm": 175,
   "FastCharge_KmH": "340",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 36837
 },
 {
   "Brand": "Opel ",
   "Model": "Ampera-e ",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 150,
   "Range_Km": 335,
   "Efficiency_WhKm": 173,
   "FastCharge_KmH": "210",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "MPV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 41906
 },
 {
   "Brand": "Porsche ",
   "Model": "Taycan 4S",
   "AccelSec": 4,
   "TopSpeed_KmH": 250,
   "Range_Km": 365,
   "Efficiency_WhKm": 195,
   "FastCharge_KmH": "730",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 102945
 },
 {
   "Brand": "Lightyear ",
   "Model": "One ",
   "AccelSec": 10,
   "TopSpeed_KmH": 150,
   "Range_Km": 575,
   "Efficiency_WhKm": 104,
   "FastCharge_KmH": "540",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Liftback",
   "Segment": "F",
   "Seats": 5,
   "PriceEuro": 149000
 },
 {
   "Brand": "Aiways ",
   "Model": "U5 ",
   "AccelSec": 9,
   "TopSpeed_KmH": 150,
   "Range_Km": 335,
   "Efficiency_WhKm": 188,
   "FastCharge_KmH": "350",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 36057
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron 55 quattro",
   "AccelSec": 5.7,
   "TopSpeed_KmH": 200,
   "Range_Km": 365,
   "Efficiency_WhKm": 237,
   "FastCharge_KmH": "590",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 79445
 },
 {
   "Brand": "Tesla ",
   "Model": "Roadster ",
   "AccelSec": 2.1,
   "TopSpeed_KmH": 410,
   "Range_Km": 970,
   "Efficiency_WhKm": 206,
   "FastCharge_KmH": "920",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Cabrio",
   "Segment": "S",
   "Seats": 4,
   "PriceEuro": 215000
 },
 {
   "Brand": "Opel ",
   "Model": "Mokka-e ",
   "AccelSec": 8.5,
   "TopSpeed_KmH": 150,
   "Range_Km": 255,
   "Efficiency_WhKm": 176,
   "FastCharge_KmH": "390",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 35000
 },
 {
   "Brand": "Skoda ",
   "Model": "Enyaq iV 80",
   "AccelSec": 8.8,
   "TopSpeed_KmH": 160,
   "Range_Km": 420,
   "Efficiency_WhKm": 183,
   "FastCharge_KmH": "560",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 40000
 },
 {
   "Brand": "Tesla ",
   "Model": "Model X Long Range",
   "AccelSec": 4.6,
   "TopSpeed_KmH": 250,
   "Range_Km": 450,
   "Efficiency_WhKm": 211,
   "FastCharge_KmH": "490",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2",
   "BodyStyle": "SUV",
   "Segment": "F",
   "Seats": 7,
   "PriceEuro": 85990
 },
 {
   "Brand": "Honda ",
   "Model": "e Advance",
   "AccelSec": 8.3,
   "TopSpeed_KmH": 145,
   "Range_Km": 170,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "190",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 35921
 },
 {
   "Brand": "DS ",
   "Model": "3 Crossback E-Tense",
   "AccelSec": 8.7,
   "TopSpeed_KmH": 150,
   "Range_Km": 250,
   "Efficiency_WhKm": 180,
   "FastCharge_KmH": "380",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 37422
 },
 {
   "Brand": "Renault ",
   "Model": "Twingo ZE",
   "AccelSec": 12.6,
   "TopSpeed_KmH": 135,
   "Range_Km": 130,
   "Efficiency_WhKm": 164,
   "FastCharge_KmH": "-",
   "RapidCharge": "No",
   "PowerTrain": "RWD",
   "PlugType": "Type 2",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 4,
   "PriceEuro": 24790
 },
 {
   "Brand": "Citroen ",
   "Model": "e-C4 ",
   "AccelSec": 9.7,
   "TopSpeed_KmH": 150,
   "Range_Km": 250,
   "Efficiency_WhKm": 180,
   "FastCharge_KmH": "380",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 40000
 },
 {
   "Brand": "Tesla ",
   "Model": "Model S Performance",
   "AccelSec": 2.5,
   "TopSpeed_KmH": 261,
   "Range_Km": 505,
   "Efficiency_WhKm": 188,
   "FastCharge_KmH": "550",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2",
   "BodyStyle": "Liftback",
   "Segment": "F",
   "Seats": 5,
   "PriceEuro": 96990
 },
 {
   "Brand": "Renault ",
   "Model": "Zoe ZE40 R110",
   "AccelSec": 11.4,
   "TopSpeed_KmH": 135,
   "Range_Km": 255,
   "Efficiency_WhKm": 161,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 29234
 },
 {
   "Brand": "Tesla ",
   "Model": "Model Y Long Range Performance",
   "AccelSec": 3.7,
   "TopSpeed_KmH": 241,
   "Range_Km": 410,
   "Efficiency_WhKm": 177,
   "FastCharge_KmH": "900",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 7,
   "PriceEuro": 65620
 },
 {
   "Brand": "Nissan ",
   "Model": "Ariya 87kWh",
   "AccelSec": 7.6,
   "TopSpeed_KmH": 160,
   "Range_Km": 440,
   "Efficiency_WhKm": 198,
   "FastCharge_KmH": "520",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 50000
 },
 {
   "Brand": "Jaguar ",
   "Model": "I-Pace ",
   "AccelSec": 4.8,
   "TopSpeed_KmH": 200,
   "Range_Km": 365,
   "Efficiency_WhKm": 232,
   "FastCharge_KmH": "340",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 75351
 },
 {
   "Brand": "Ford ",
   "Model": "Mustang Mach-E ER RWD",
   "AccelSec": 7,
   "TopSpeed_KmH": 180,
   "Range_Km": 450,
   "Efficiency_WhKm": 200,
   "FastCharge_KmH": "430",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 54475
 },
 {
   "Brand": "Porsche ",
   "Model": "Taycan 4S Plus",
   "AccelSec": 4,
   "TopSpeed_KmH": 250,
   "Range_Km": 425,
   "Efficiency_WhKm": 197,
   "FastCharge_KmH": "890",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 109302
 },
 {
   "Brand": "Nissan ",
   "Model": "e-NV200 Evalia ",
   "AccelSec": 14,
   "TopSpeed_KmH": 123,
   "Range_Km": 190,
   "Efficiency_WhKm": 200,
   "FastCharge_KmH": "190",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 1 CHAdeMO",
   "BodyStyle": "SPV",
   "Segment": "N",
   "Seats": 7,
   "PriceEuro": 33246
 },
 {
   "Brand": "Tesla ",
   "Model": "Cybertruck Dual Motor",
   "AccelSec": 5,
   "TopSpeed_KmH": 190,
   "Range_Km": 460,
   "Efficiency_WhKm": 261,
   "FastCharge_KmH": "710",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Pickup",
   "Segment": "N",
   "Seats": 6,
   "PriceEuro": 55000
 },
 {
   "Brand": "Renault ",
   "Model": "Kangoo Maxi ZE 33",
   "AccelSec": 22.4,
   "TopSpeed_KmH": 130,
   "Range_Km": 160,
   "Efficiency_WhKm": 194,
   "FastCharge_KmH": "-",
   "RapidCharge": "No",
   "PowerTrain": "FWD",
   "PlugType": "Type 2",
   "BodyStyle": "SPV",
   "Segment": "N",
   "Seats": 5,
   "PriceEuro": 38000
 },
 {
   "Brand": "Ford ",
   "Model": "Mustang Mach-E ER AWD",
   "AccelSec": 6,
   "TopSpeed_KmH": 180,
   "Range_Km": 430,
   "Efficiency_WhKm": 209,
   "FastCharge_KmH": "410",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 62900
 },
 {
   "Brand": "BMW ",
   "Model": "i3s 120 Ah",
   "AccelSec": 6.9,
   "TopSpeed_KmH": 160,
   "Range_Km": 230,
   "Efficiency_WhKm": 165,
   "FastCharge_KmH": "260",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 41526
 },
 {
   "Brand": "Skoda ",
   "Model": "Enyaq iV 80X",
   "AccelSec": 7,
   "TopSpeed_KmH": 160,
   "Range_Km": 400,
   "Efficiency_WhKm": 193,
   "FastCharge_KmH": "540",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 45000
 },
 {
   "Brand": "Porsche ",
   "Model": "Taycan Cross Turismo ",
   "AccelSec": 3.5,
   "TopSpeed_KmH": 250,
   "Range_Km": 385,
   "Efficiency_WhKm": 217,
   "FastCharge_KmH": "770",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Station",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 150000
 },
 {
   "Brand": "Byton ",
   "Model": "M-Byte 95 kWh 4WD",
   "AccelSec": 5.5,
   "TopSpeed_KmH": 190,
   "Range_Km": 390,
   "Efficiency_WhKm": 244,
   "FastCharge_KmH": "460",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 64000
 },
 {
   "Brand": "Sono ",
   "Model": "Sion ",
   "AccelSec": 9,
   "TopSpeed_KmH": 140,
   "Range_Km": 225,
   "Efficiency_WhKm": 156,
   "FastCharge_KmH": "270",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 25500
 },
 {
   "Brand": "Kia ",
   "Model": "e-Niro 39 kWh",
   "AccelSec": 9.8,
   "TopSpeed_KmH": 155,
   "Range_Km": 235,
   "Efficiency_WhKm": 167,
   "FastCharge_KmH": "230",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 34400
 },
 {
   "Brand": "Audi ",
   "Model": "Q4 Sportback e-tron ",
   "AccelSec": 6.3,
   "TopSpeed_KmH": 180,
   "Range_Km": 410,
   "Efficiency_WhKm": 188,
   "FastCharge_KmH": "550",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 57500
 },
 {
   "Brand": "Smart ",
   "Model": "EQ forfour ",
   "AccelSec": 12.7,
   "TopSpeed_KmH": 130,
   "Range_Km": 95,
   "Efficiency_WhKm": 176,
   "FastCharge_KmH": "-",
   "RapidCharge": "No",
   "PowerTrain": "RWD",
   "PlugType": "Type 2",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 4,
   "PriceEuro": 22030
 },
 {
   "Brand": "Ford ",
   "Model": "Mustang Mach-E SR AWD",
   "AccelSec": 6,
   "TopSpeed_KmH": 180,
   "Range_Km": 340,
   "Efficiency_WhKm": 206,
   "FastCharge_KmH": "360",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 54000
 },
 {
   "Brand": "Porsche ",
   "Model": "Taycan Turbo",
   "AccelSec": 3.2,
   "TopSpeed_KmH": 260,
   "Range_Km": 390,
   "Efficiency_WhKm": 215,
   "FastCharge_KmH": "810",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Sedan",
   "Segment": "F",
   "Seats": 4,
   "PriceEuro": 148301
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.3 1st",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 160,
   "Range_Km": 340,
   "Efficiency_WhKm": 171,
   "FastCharge_KmH": "470",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 38987
 },
 {
   "Brand": "Tesla ",
   "Model": "Model X Performance",
   "AccelSec": 2.8,
   "TopSpeed_KmH": 250,
   "Range_Km": 440,
   "Efficiency_WhKm": 216,
   "FastCharge_KmH": "480",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2",
   "BodyStyle": "SUV",
   "Segment": "F",
   "Seats": 7,
   "PriceEuro": 102990
 },
 {
   "Brand": "Smart ",
   "Model": "EQ fortwo coupe",
   "AccelSec": 11.6,
   "TopSpeed_KmH": 130,
   "Range_Km": 100,
   "Efficiency_WhKm": 167,
   "FastCharge_KmH": "-",
   "RapidCharge": "No",
   "PowerTrain": "RWD",
   "PlugType": "Type 2",
   "BodyStyle": "Hatchback",
   "Segment": "A",
   "Seats": 2,
   "PriceEuro": 21387
 },
 {
   "Brand": "Ford ",
   "Model": "Mustang Mach-E SR RWD",
   "AccelSec": 6.6,
   "TopSpeed_KmH": 180,
   "Range_Km": 360,
   "Efficiency_WhKm": 194,
   "FastCharge_KmH": "380",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "D",
   "Seats": 5,
   "PriceEuro": 46900
 },
 {
   "Brand": "Mercedes ",
   "Model": "EQV 300 Long",
   "AccelSec": 10,
   "TopSpeed_KmH": 140,
   "Range_Km": 330,
   "Efficiency_WhKm": 273,
   "FastCharge_KmH": "290",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SPV",
   "Segment": "N",
   "Seats": 7,
   "PriceEuro": 70631
 },
 {
   "Brand": "Fiat ",
   "Model": "500e Hatchback",
   "AccelSec": 9,
   "TopSpeed_KmH": 150,
   "Range_Km": 250,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "330",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 34900
 },
 {
   "Brand": "Tesla ",
   "Model": "Cybertruck Single Motor",
   "AccelSec": 7,
   "TopSpeed_KmH": 180,
   "Range_Km": 390,
   "Efficiency_WhKm": 256,
   "FastCharge_KmH": "740",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Pickup",
   "Segment": "N",
   "Seats": 6,
   "PriceEuro": 45000
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron Sportback 50 quattro",
   "AccelSec": 6.8,
   "TopSpeed_KmH": 190,
   "Range_Km": 295,
   "Efficiency_WhKm": 219,
   "FastCharge_KmH": "470",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 69551
 },
 {
   "Brand": "Skoda ",
   "Model": "Enyaq iV vRS",
   "AccelSec": 6.2,
   "TopSpeed_KmH": 180,
   "Range_Km": 400,
   "Efficiency_WhKm": 193,
   "FastCharge_KmH": "540",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 47500
 },
 {
   "Brand": "Skoda ",
   "Model": "Enyaq iV 60",
   "AccelSec": 9,
   "TopSpeed_KmH": 160,
   "Range_Km": 320,
   "Efficiency_WhKm": 181,
   "FastCharge_KmH": "440",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 37500
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron S 55 quattro",
   "AccelSec": 4.5,
   "TopSpeed_KmH": 210,
   "Range_Km": 320,
   "Efficiency_WhKm": 270,
   "FastCharge_KmH": "510",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 93800
 },
 {
   "Brand": "Smart ",
   "Model": "EQ fortwo cabrio",
   "AccelSec": 11.9,
   "TopSpeed_KmH": 130,
   "Range_Km": 95,
   "Efficiency_WhKm": 176,
   "FastCharge_KmH": "-",
   "RapidCharge": "No",
   "PowerTrain": "RWD",
   "PlugType": "Type 2",
   "BodyStyle": "Cabrio",
   "Segment": "A",
   "Seats": 2,
   "PriceEuro": 24565
 },
 {
   "Brand": "Kia ",
   "Model": "e-Soul 64 kWh",
   "AccelSec": 7.9,
   "TopSpeed_KmH": 167,
   "Range_Km": 365,
   "Efficiency_WhKm": 175,
   "FastCharge_KmH": "320",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 36837
 },
 {
   "Brand": "Nissan ",
   "Model": "Ariya e-4ORCE 87kWh",
   "AccelSec": 5.7,
   "TopSpeed_KmH": 200,
   "Range_Km": 420,
   "Efficiency_WhKm": 207,
   "FastCharge_KmH": "500",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 57500
 },
 {
   "Brand": "Fiat ",
   "Model": "500e Convertible",
   "AccelSec": 9,
   "TopSpeed_KmH": 150,
   "Range_Km": 250,
   "Efficiency_WhKm": 168,
   "FastCharge_KmH": "330",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Cabrio",
   "Segment": "B",
   "Seats": 4,
   "PriceEuro": 37900
 },
 {
   "Brand": "Volkswagen ",
   "Model": "ID.3 Pro Performance",
   "AccelSec": 7.3,
   "TopSpeed_KmH": 160,
   "Range_Km": 340,
   "Efficiency_WhKm": 171,
   "FastCharge_KmH": "470",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 35575
 },
 {
   "Brand": "Kia ",
   "Model": "e-Soul 39 kWh",
   "AccelSec": 9.9,
   "TopSpeed_KmH": 157,
   "Range_Km": 230,
   "Efficiency_WhKm": 170,
   "FastCharge_KmH": "220",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "B",
   "Seats": 5,
   "PriceEuro": 33133
 },
 {
   "Brand": "Byton ",
   "Model": "M-Byte 72 kWh 2WD",
   "AccelSec": 7.5,
   "TopSpeed_KmH": 190,
   "Range_Km": 325,
   "Efficiency_WhKm": 222,
   "FastCharge_KmH": "420",
   "RapidCharge": "Yes",
   "PowerTrain": "RWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 53500
 },
 {
   "Brand": "Nissan ",
   "Model": "Ariya 63kWh",
   "AccelSec": 7.5,
   "TopSpeed_KmH": 160,
   "Range_Km": 330,
   "Efficiency_WhKm": 191,
   "FastCharge_KmH": "440",
   "RapidCharge": "Yes",
   "PowerTrain": "FWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 45000
 },
 {
   "Brand": "Audi ",
   "Model": "e-tron S Sportback 55 quattro",
   "AccelSec": 4.5,
   "TopSpeed_KmH": 210,
   "Range_Km": 335,
   "Efficiency_WhKm": 258,
   "FastCharge_KmH": "540",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 96050
 },
 {
   "Brand": "Nissan ",
   "Model": "Ariya e-4ORCE 63kWh",
   "AccelSec": 5.9,
   "TopSpeed_KmH": 200,
   "Range_Km": 325,
   "Efficiency_WhKm": 194,
   "FastCharge_KmH": "440",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 50000
 },
 {
   "Brand": "Nissan ",
   "Model": "Ariya e-4ORCE 87kWh Performance",
   "AccelSec": 5.1,
   "TopSpeed_KmH": 200,
   "Range_Km": 375,
   "Efficiency_WhKm": 232,
   "FastCharge_KmH": "450",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "Hatchback",
   "Segment": "C",
   "Seats": 5,
   "PriceEuro": 65000
 },
 {
   "Brand": "Byton ",
   "Model": "M-Byte 95 kWh 2WD",
   "AccelSec": 7.5,
   "TopSpeed_KmH": 190,
   "Range_Km": 400,
   "Efficiency_WhKm": 238,
   "FastCharge_KmH": "480",
   "RapidCharge": "Yes",
   "PowerTrain": "AWD",
   "PlugType": "Type 2 CCS",
   "BodyStyle": "SUV",
   "Segment": "E",
   "Seats": 5,
   "PriceEuro": 62000
 }
]
`;

export const dataVehiclesElectricEU = JSON.parse(jsonChunk);

